name: haizzy
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  firebase_storage: ^12.4.4
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  get_storage: ^2.1.1
  logger: ^2.5.0
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/on_boarding_images
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/logos/h-store-splash-logo-white.png
  image_dark: assets/logos/h-store-splash-logo-black.png
  android_12:
    color: "#ffffff"
    color_dark: "#272727"
    image: assets/logos/h-store-splash-logo-white.png
    image_dark: assets/logos/h-store-splash-logo-black.png
  ios: true
  web: false